# Generated by Django 5.1.5 on 2025-01-26 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '(99) 99999-9999'.", regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')])),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, message='Estado deve ter 2 caracteres.')])),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message="CEP deve estar no formato: '99999-999'.", regex='^\\d{5}-\\d{3}$')])),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="CPF deve estar no formato: '999.999.999-99'.", regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('rg', models.CharField(max_length=12)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
