# Generated by Django 5.1.5 on 2025-01-27 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('C', 'Canino'), ('F', 'Felino'), ('B', 'Bovino'), ('E', 'Equino'), ('A', 'Aves'), ('S', 'Silvestres'), ('O', 'Outros')], default='C', max_length=1)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='tutores.tutor')),
            ],
        ),
    ]
