# Generated by Django 5.1.5 on 2025-01-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
