# Generated by Django 5.1.5 on 2025-01-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0003_delete_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
    ]
