# Generated by Django 5.1.5 on 2025-01-27 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_delete_tutorcliente'),
        ('tutores', '0004_alter_tutor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutores.tutor')),
            ],
            options={
                'verbose_name': 'Cliente do Tutor',
                'verbose_name_plural': 'Clientes do Tutor',
            },
        ),
    ]
