# Generated by Django 5.1.5 on 2025-01-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0005_clientestutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientesTutor',
        ),
    ]
