# Generated by Django 5.1.5 on 2025-02-03 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0006_delete_clientestutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="CPF deve estar no formato: '999.999.999-99'.", regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
