# Generated by Django 5.1.5 on 2025-01-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_delete_tutorcliente'),
        ('tutores', '0006_delete_clientestutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('comportamento', models.CharField(choices=[('D', 'Depressivo'), ('E', 'Excitado')], max_length=1)),
                ('voz', models.CharField(max_length=10, verbose_name='Voz')),
                ('alimentacao', models.CharField(choices=[('N', 'Normal'), ('A', 'Alterada')], max_length=10, verbose_name='Alimentação')),
                ('apetite', models.CharField(choices=[('B', 'Bom'), ('R', 'Reduzido')], max_length=10)),
                ('preensao', models.CharField(max_length=10, verbose_name='Prensão')),
                ('mastigacao', models.CharField(max_length=10, verbose_name='Mastigação')),
                ('degluticao', models.CharField(max_length=10, verbose_name='Deglutição')),
                ('vomitos', models.CharField(max_length=10, verbose_name='Vômitos')),
                ('regurgitacao', models.CharField(max_length=10, verbose_name='Regurgitação')),
                ('excrecao', models.CharField(default='N/A', max_length=10, verbose_name='Excreção')),
                ('constipacao', models.CharField(default='N/A', max_length=10, verbose_name='Constipação')),
                ('diarreia', models.CharField(max_length=10, verbose_name='Diarreia')),
                ('miccao', models.CharField(max_length=10, verbose_name='Micção')),
                ('condicao_corporal', models.CharField(choices=[('C', 'Caquético'), ('M', 'Magro'), ('N', 'Normal'), ('S', 'Sobrepeso'), ('O', 'Obeso')], default='N', max_length=1, verbose_name='Condição Corporal')),
                ('postura', models.CharField(default='N/A', max_length=20, verbose_name='Postura')),
                ('marcha', models.CharField(default='N/A', max_length=25, verbose_name='Marcha')),
                ('pele', models.CharField(default='N/A', max_length=25, verbose_name='Pele')),
                ('cabeca', models.CharField(default='N/A', max_length=25, verbose_name='Cabeça')),
                ('olhos', models.CharField(default='N/A', max_length=25, verbose_name='Olhos')),
                ('salivacao', models.CharField(default='N/A', max_length=25, verbose_name='Salivação')),
                ('pescoco', models.CharField(default='N/A', max_length=25, verbose_name='Pescoço')),
                ('torax', models.CharField(default='N/A', max_length=25, verbose_name='Torax')),
                ('abdomem', models.CharField(default='N/A', max_length=25, verbose_name='Abdomem')),
                ('genitalia_externa', models.CharField(default='N/A', max_length=25, verbose_name='Genitália Externa')),
                ('glandulas_mamarias', models.CharField(default='N/A', max_length=25, verbose_name='Glândulas Mamárias')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperatura')),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frequência Cardíaca')),
                ('frequencia_respiratoria', models.IntegerField(blank=True, null=True, verbose_name='Frequência Respiratória')),
                ('circ_periferica_hidratacao', models.TextField(default='N/A', verbose_name='Circulação Periférica e Hidratação')),
                ('mucosas', models.CharField(choices=[('P', 'Pálidas'), ('I', 'Ictéricas'), ('N', 'Normal'), ('C', 'Congesta'), ('H', 'Hipocorada')], default='N', max_length=1, verbose_name='Mucosas')),
                ('torax_perto', models.TextField(default='N/A', verbose_name='Torax')),
                ('abdomem_perto', models.TextField(default='N/A', verbose_name='Abdomem Perto')),
                ('cabeca_pescoco', models.TextField(default='N/A', verbose_name='Cabeça e Pescoço')),
                ('sistema_urinario', models.TextField(default='N/A', verbose_name='Sistema Urinário')),
                ('trato_reprodutor', models.TextField(default='N/A', verbose_name='Trato Reprodutor')),
                ('glandulas_mamarias_perto', models.TextField(default='N/A', verbose_name='Glândulas Mamárias')),
                ('sist_musculo_esqueletico', models.TextField(default='N/A', verbose_name='Sistema Músculo Esquelético')),
                ('sistema_nervoso', models.TextField(default='N/A', verbose_name='Sistema Nervoso')),
                ('diagnostico', models.TextField(default='N/A', verbose_name='Diagnóstico')),
                ('tratamento', models.TextField(default='N/A', verbose_name='Tratamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_cliente', to='clientes.clientes')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_tutor', to='tutores.tutor')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
