# Generated by Django 5.1.5 on 2025-01-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, null=True),
        ),
    ]
