# Generated by Django 5.1.5 on 2025-01-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_tutorcliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorCliente',
        ),
    ]
